spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moviemingle?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username : root
    password : 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
