USE world;

CREATE TABLE user (
  user_id INT AUTO_INCREMENT PRIMARY KEY,  -- 유저 식별번호
  id VARCHAR(255) NOT NULL,  -- 아이디
  password VARCHAR(255) NOT NULL,  -- 비밀번호
  name VARCHAR(255) NOT NULL,  -- 이름
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 생성일
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  -- 변경일
);